@startuml
title Browse Restaurant

actor Customer

' Boundary Object
boundary "Restaurant Browser" as browser

' Control Object
control "Restaurant Controller" as restaurantCtrol
control "Menu Controller" as menuCtrl

' Entity Object
entity "Restaurant" as restaurant
entity "MenuItem" as menuItem

' Flow
Customer -> browser : request restaurants
browser -> restaurantCtrol : get restaurants
restaurantCtrol -> restaurant : retrieve restaurant list
restaurant -> restaurantCtrol : restaurant data
restaurantCtrol -> browser : display restaurants
browser -> Customer : show restaurants
Customer -> browser : select restaurant
browser -> menuCtrl : get menu
menuCtrl -> menuItem : retrieve menu items
menuItem -> menuCtrl : menu data
menuCtrl -> browser : display menu
browser -> Customer : show menu 

@enduml