@startuml
left to right direction

title Add to Cart

actor Customer

' Boundary Object
boundary "Menu Display" as menuDisplay

' Control Object
control "Authetication Controller" as authCtrl
control "Cart Controller" as cartCtrl

' Entity Object
entity "Customer Data" as customerEntity
entity "Cart Data" as cart
entity "MenuItem Data" as menuItem

' Relationships
Customer -- menuDisplay : select item from
menuDisplay -- authCtrl : verifies through
menuDisplay -- cartCtrl : sends selections to
authCtrl -- customerEntity : authentication against
cartCtrl -- cart : updates
cartCtrl -- menuItem : retrieve from

note bottom of menuDisplay
    Interface for selecting
    and adding menu items
end note

note bottom of authCtrl
    Verifies user is
    logged in (included)
end note

note bottom of cartCtrl
    Manages cart operations
    and updates
end note

note bottom of cart
    Stroes user's
    selected items
end note

@enduml